import {
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BellOutlined,
  BookOutlined,
  BulbOutlined,
  CalendarOutlined,
  CarOutlined,
  CommentOutlined,
  ContactsOutlined,
  CreditCardOutlined,
  DatabaseOutlined,
  EnvironmentOutlined,
  FileImageOutlined,
  FileTextOutlined,
  FlagOutlined,
  FolderOpenOutlined,
  GiftOutlined,
  GlobalOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  LinkOutlined,
  MailOutlined,
  MessageOutlined,
  NotificationOutlined,
  PictureOutlined,
  ProductOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PushpinOutlined,
  ReadOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SmileOutlined,
  SolutionOutlined,
  StarOutlined,
  TagOutlined,
  TeamOutlined,
  ToolOutlined,
  TrophyOutlined,
  UnorderedListOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WalletOutlined,
} from '@ant-design/icons'
import type { ComponentType } from 'react'

export const DEFAULT_MODEL_ICON = 'AppstoreOutlined'

export const MODEL_ICON_OPTIONS: Array<{ value: string; label: string; component: ComponentType }> = [
  { value: 'AppstoreOutlined', label: '应用', component: AppstoreOutlined },
  { value: 'DatabaseOutlined', label: '数据', component: DatabaseOutlined },
  { value: 'FolderOpenOutlined', label: '目录', component: FolderOpenOutlined },
  { value: 'UnorderedListOutlined', label: '列表', component: UnorderedListOutlined },
  { value: 'ProfileOutlined', label: '档案', component: ProfileOutlined },
  { value: 'ProjectOutlined', label: '项目', component: ProjectOutlined },
  { value: 'FileTextOutlined', label: '文档', component: FileTextOutlined },
  { value: 'ReadOutlined', label: '阅读', component: ReadOutlined },
  { value: 'BookOutlined', label: '书籍', component: BookOutlined },
  { value: 'AuditOutlined', label: '审核', component: AuditOutlined },
  { value: 'SolutionOutlined', label: '档案夹', component: SolutionOutlined },
  { value: 'IdcardOutlined', label: '证件', component: IdcardOutlined },
  { value: 'UserOutlined', label: '用户', component: UserOutlined },
  { value: 'TeamOutlined', label: '团队', component: TeamOutlined },
  { value: 'ContactsOutlined', label: '联系人', component: ContactsOutlined },
  { value: 'ShoppingOutlined', label: '订单', component: ShoppingOutlined },
  { value: 'ShoppingCartOutlined', label: '购物车', component: ShoppingCartOutlined },
  { value: 'ProductOutlined', label: '商品', component: ProductOutlined },
  { value: 'ShopOutlined', label: '店铺', component: ShopOutlined },
  { value: 'GiftOutlined', label: '礼品', component: GiftOutlined },
  { value: 'TagOutlined', label: '标签', component: TagOutlined },
  { value: 'CreditCardOutlined', label: '支付', component: CreditCardOutlined },
  { value: 'WalletOutlined', label: '钱包', component: WalletOutlined },
  { value: 'BankOutlined', label: '银行', component: BankOutlined },
  { value: 'TrophyOutlined', label: '奖励', component: TrophyOutlined },
  { value: 'StarOutlined', label: '收藏', component: StarOutlined },
  { value: 'BellOutlined', label: '通知', component: BellOutlined },
  { value: 'NotificationOutlined', label: '公告', component: NotificationOutlined },
  { value: 'MessageOutlined', label: '消息', component: MessageOutlined },
  { value: 'CommentOutlined', label: '评论', component: CommentOutlined },
  { value: 'MailOutlined', label: '邮件', component: MailOutlined },
  { value: 'PictureOutlined', label: '图片', component: PictureOutlined },
  { value: 'FileImageOutlined', label: '图集', component: FileImageOutlined },
  { value: 'VideoCameraOutlined', label: '视频', component: VideoCameraOutlined },
  { value: 'CalendarOutlined', label: '日历', component: CalendarOutlined },
  { value: 'ScheduleOutlined', label: '日程', component: ScheduleOutlined },
  { value: 'EnvironmentOutlined', label: '位置', component: EnvironmentOutlined },
  { value: 'GlobalOutlined', label: '全球', component: GlobalOutlined },
  { value: 'HomeOutlined', label: '首页', component: HomeOutlined },
  { value: 'CarOutlined', label: '车辆', component: CarOutlined },
  { value: 'InboxOutlined', label: '收件', component: InboxOutlined },
  { value: 'LinkOutlined', label: '链接', component: LinkOutlined },
  { value: 'PushpinOutlined', label: '钉住', component: PushpinOutlined },
  { value: 'FlagOutlined', label: '旗标', component: FlagOutlined },
  { value: 'BulbOutlined', label: '提示', component: BulbOutlined },
  { value: 'SmileOutlined', label: '心情', component: SmileOutlined },
  { value: 'ToolOutlined', label: '工具', component: ToolOutlined },
  { value: 'SettingOutlined', label: '设置', component: SettingOutlined },
]

const iconMap = new Map(MODEL_ICON_OPTIONS.map((item) => [item.value, item.component]))

export function getModelIconComponent(value?: string) {
  if (value && iconMap.has(value)) {
    return iconMap.get(value) as ComponentType
  }
  return iconMap.get(DEFAULT_MODEL_ICON) as ComponentType
}
