/**
 * 云函数部署副本。
 *
 * 注意：
 * - 该文件需要随 runtime 云函数一起部署
 * - 当前内容应与前端配置源保持一致
 * - 修改字段类型或字段能力后，请手动同步此文件
 */
module.exports = {
  fields: [
    {
      value: 'text',
      label: '文本',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'text',
      displayRenderer: 'text',
      supports: {
        minLength: true,
        maxLength: true,
        sortable: true,
      },
    },
    {
      value: 'textarea',
      label: '多行文本',
      enabledInModelCreate: true,
      searchRenderer: 'textarea',
      formRenderer: 'textarea',
      displayRenderer: 'textarea',
      supports: {
        minLength: true,
        maxLength: true,
        sortable: true,
      },
    },
    {
      value: 'richtext',
      label: '富文本',
      enabledInModelCreate: true,
      searchRenderer: 'textarea',
      formRenderer: 'textarea',
      displayRenderer: 'richtext',
      supports: {
        minLength: true,
        maxLength: true,
        sortable: true,
      },
    },
    {
      value: 'markdown',
      label: 'Markdown',
      enabledInModelCreate: true,
      searchRenderer: 'textarea',
      formRenderer: 'textarea',
      displayRenderer: 'markdown',
      supports: {
        minLength: true,
        maxLength: true,
        sortable: true,
      },
    },
    {
      value: 'number',
      label: '数字',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'text',
      displayRenderer: 'number',
      supports: {
        minValue: true,
        maxValue: true,
        sortable: true,
      },
    },
    {
      value: 'boolean',
      label: '布尔值',
      enabledInModelCreate: true,
      searchRenderer: 'boolean',
      formRenderer: 'boolean',
      displayRenderer: 'boolean',
      supports: {
        sortable: true,
      },
    },
    {
      value: 'date',
      label: '日期',
      enabledInModelCreate: true,
      searchRenderer: 'date',
      formRenderer: 'date',
      displayRenderer: 'date',
      supports: {
        sortable: true,
      },
    },
    {
      value: 'datetime',
      label: '日期时间',
      enabledInModelCreate: true,
      searchRenderer: 'datetime',
      formRenderer: 'datetime',
      displayRenderer: 'datetime',
      supports: {
        sortable: true,
      },
    },
    {
      value: 'enum',
      label: '枚举',
      enabledInModelCreate: true,
      searchRenderer: 'select',
      formRenderer: 'select',
      displayRenderer: 'select',
      supports: {
        enumOptions: true,
        enumValueType: true,
        sortable: true,
      },
    },
    {
      value: 'relation',
      label: '单模型（单记录）',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'relationOne',
      displayRenderer: 'relationOne',
      supports: {
        relationModelCollection: true,
        relationDisplayFields: true,
      },
    },
    {
      value: 'multiRelation',
      label: '单模型（多记录）',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'relationMany',
      displayRenderer: 'relationMany',
      supports: {
        relationModelCollection: true,
        relationDisplayFields: true,
        minItems: true,
        maxItems: true,
      },
    },
    {
      value: 'polyRelation',
      label: '多模型（单记录）',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'polyRelation',
      displayRenderer: 'polyRelation',
      supports: {
        relationModelCollections: true,
        polyRelationDisplayMap: true,
      },
    },
    {
      value: 'multiPolyRelation',
      label: '多模型（多记录）',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'multiPolyRelation',
      displayRenderer: 'multiPolyRelation',
      supports: {
        relationModelCollections: true,
        polyRelationDisplayMap: true,
        polyRelationLimitMap: true,
      },
    },
    {
      value: 'array',
      label: '数组',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'array',
      displayRenderer: 'array',
      supports: {
        minItems: true,
        maxItems: true,
        itemType: true,
      },
    },
    {
      value: 'image',
      label: '图片',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'image',
      displayRenderer: 'image',
      supports: {
        allowMultiple: true,
        minItems: true,
        maxItems: true,
        accept: true,
        maxFileSizeMB: true,
        assetStorageMode: true,
      },
      defaultAccept: ['image/*'],
    },
    {
      value: 'file',
      label: '文件',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'file',
      displayRenderer: 'file',
      supports: {
        allowMultiple: true,
        minItems: true,
        maxItems: true,
        accept: true,
        maxFileSizeMB: true,
        assetStorageMode: true,
      },
      defaultAccept: ['.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx', '.txt', '.md', '.csv', '.zip', '.rar', '.7z'],
    },
    {
      value: 'video',
      label: '视频',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'video',
      displayRenderer: 'video',
      supports: {
        allowMultiple: true,
        minItems: true,
        maxItems: true,
        accept: true,
        maxFileSizeMB: true,
        assetStorageMode: true,
      },
      defaultAccept: ['video/*'],
    },
    {
      value: 'audio',
      label: '音频',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'audio',
      displayRenderer: 'audio',
      supports: {
        allowMultiple: true,
        minItems: true,
        maxItems: true,
        accept: true,
        maxFileSizeMB: true,
        assetStorageMode: true,
      },
      defaultAccept: ['audio/*'],
    },
    {
      value: 'json',
      label: 'JSON',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'json',
      displayRenderer: 'json',
      supports: {
        jsonValueType: true,
      },
    },
    {
      value: 'location',
      label: '位置',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'json',
      displayRenderer: 'json',
      supports: {
        locationCoordinateSystem: true,
        locationRequireAddress: true,
        locationRequireName: true,
        locationStorageMode: true,
        locationFieldMapping: true,
      },
    },
    {
      value: 'address',
      label: '地址',
      enabledInModelCreate: true,
      searchRenderer: 'text',
      formRenderer: 'json',
      displayRenderer: 'json',
      supports: {
        addressGranularity: true,
        addressStorageMode: true,
        addressFieldMapping: true,
      },
    },
  ],
}
